WEB_CONTENT_BLOCKS = (
    {'key': 'firstscreen-header'},
    {'key': 'firstscreen-subheader'},
    {'key': 'firstscreen-description'},
    {'key': 'vision-header'},
    {'key': 'vision-description'},
    {'key': 'about-header'},
    {'key': 'about-subheader'},
    {'key': 'about-description'},
    {'key': 'feature1-header'},
    {'key': 'feature1-description'},
    {'key': 'feature2-header'},
    {'key': 'feature2-description'},
    {'key': 'feature3-header'},
    {'key': 'feature3-description'},
    {'key': 'footer-header'},
)
